version: 2.1
orbs:
  github-app-token: tyba-energy/github-app-token@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

executors:
  base:
    docker:
      - image: cimg/base:current
  node:
    docker:
      - image: cimg/node:22.14
  ruby:
    docker:
      - image: cimg/ruby:3.3
  python:
    docker:
      - image: cimg/python:3.13

commands:
  fetch-github-app-token:
    steps:
      - github-app-token/fetch-token:
          app_id: $GITHUB_APP_ID
          installation_id: $GITHUB_APP_INSTALLATION_ID
          base64_private_key: $GITHUB_APP_PRIVATE_KEY

jobs:
  command-tests:
    parameters:
      run_executor:
        type: executor
        default: base
    executor: << parameters.run_executor >>
    steps:
      - checkout
      - fetch-github-app-token
      - run: echo "${GITHUB_TOKEN:0:12}..."

workflows:
  test-deploy:
    jobs:
      - command-tests:
          filters: *filters
      - command-tests:
          name: command-tests-node
          run_executor: node
          filters: *filters
      - command-tests:
          name: command-tests-ruby
          run_executor: ruby
          filters: *filters
      - command-tests:
          name: command-tests-python
          run_executor: python
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: tyba-energy/github-app-token
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - command-tests-node
            - command-tests-ruby
            - command-tests-python
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
